### PR TITLE
Add a GitHub Action that finds Python 3 syntax errors

### PR DESCRIPTION
**Pull request by cclauss**
https://github.com/marketplace/actions/python-syntax-checker

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks! We already have Flake8 running on both Travis CI and Azure Pipelines, but I've not tried GitHub Actions before so I'm curious to see how this works.

Should it report a pass/fail somewhere? I don't see it amongst the "12 successful checks" list. Or does it need merging first?

> [github.com/marketplace/actions/python-syntax-checker](https://github.com/marketplace/actions/python-syntax-checker)

This gives a 404 for me.

**Comment by cclauss** [comment]
Yes.  It runs on my repos but I guess it is not yet “public” for those who are not in the beta.  

https://github.com/cclauss/Ten-lines-or-less/commits/master

**Comment by hugovk** [comment]
OK, signed up and will wait for access!

image

**Comment by cclauss** [comment]
Did you get into the beta program yet?

**Comment by hugovk** [comment]
Still waiting.

> This account is already on the waitlist for the GitHub Actions Beta! We'll notify you when we've enabled it on your account. Make sure your primary email address is up-to-date so we can get a hold of you.

https://github.com/features/actions/signup/?account=hugovk

**Comment by hugovk** [comment]
After 6.5 months, I'm now in the beta!

Does this need any updates? 

I'll close and reopen this PR to see if it will trigger it.

**Comment by cclauss** [comment]
My sense is that this PR is obsolete in the face of #70

**Pull request closed without merging**
