### PR TITLE
Add validators for 'python_major' and 'python_minor' arguments

### PR DESCRIPTION
**Pull request by lnxpy**
- [x] `argparse` validators implementation
- [x] add cli tests

### CODE REVIEW

**Comment by hugovk** [comment]
Please could you add tests in https://github.com/hugovk/pypistats/blob/main/tests/test_cli.py?

**Comment by lnxpy** [comment]
Hi @hugovk. Would you work on the remaining tasks?! They look a bit confusing to me actually. Sorry for that.

**Comment by hugovk** [comment]
The invalid one is similar:

```python
@pytest.mark.parametrize("test_input", ["2.7", "3.9", "3.11", "-5", "pillow"])
def test__python_major_version_invalid(test_input) -> None:
    # Act / Assert
    with pytest.raises(argparse.ArgumentTypeError):
        cli._python_major_version(test_input)
```

Except that `_python_major_version` won't return a value for invalid input, so we don't assert the output is a value, we use the `pytest.raises` context manager to check the mentioned exception is raised.

Then we have a similar pair for `_python_minor_version`.

**Comment by hugovk** [comment]
Would you to look at exception handling for empty data or shall I check that?

We could actually merge this PR as it is, it's nicely self-contained, and do that bit in another PR.

**Comment by lnxpy** [comment]
I actually thought that you want me to add tests for the actual CLI arguments like the `args.python_major`, `args.python_minor`, and `args.system`. I could add tests for that small validator piece. Thanks for your complete explanation though. :))

**Comment by lnxpy** [comment]
Yes indeed. We can have that exception handling in another PR. I unlinked this PR. By merging this PR, the issue won't get closed anymore. Would you please work on that part too?! I looked over the codebase days ago and that was a bit hard to figure out its parts. Keep in mind that I looked over it with the mindset that I talked about in #401.

For the sake of simplicity, we can have some refactoring and improvements next up. 🍻

**Comment by hugovk** [comment]
Sounds good 👍

**Pull request merged**
