### PR TITLE
Declare support for Python 3.9

### PR DESCRIPTION
**Pull request by liisberg**
Please see #171 for further information.

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks!

As mentioned in https://github.com/hugovk/pypistats/issues/171#issuecomment-703604205, let's just go for the `setup.py` changes for now.

**Comment by liisberg** [comment]
All tests [now pass](https://github.com/liisberg/pypistats/runs/1215556870)! Hurray!

**Comment by hugovk** [comment]
> All tests [now pass](https://github.com/liisberg/pypistats/runs/1215556870)! Hurray!


?

```
==================================== ERRORS ====================================
___________________ ERROR collecting tests/test_pypistats.py ___________________
tests/test_pypistats.py:22: in <module>
    import numpy
.tox/py/lib/python3.9/site-packages/numpy/__init__.py:286: in <module>
    raise RuntimeError(msg)
E   RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
E   RankWarning: Polyfit may be poorly conditioned
------------------------------- Captured stderr --------------------------------
init_dgelsd failed init

---------- coverage: platform darwin, python 3.9.0-final-0 -----------
Coverage XML written to file coverage.xml

=========================== short test summary info ============================
ERROR tests/test_pypistats.py - RuntimeError: Polyfit sanity test emitted a w...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 2.40s ===============================
ERROR: InvocationError for command /Users/runner/work/pypistats/pypistats/.tox/py/bin/python -m pytest --cov pypistats --cov tests --cov-report xml (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   py: commands failed
Error: Process completed with exit code 1.
```

**Comment by liisberg** [comment]
Oh, shoot - my bad. Didn't see the error for macOS.

**Comment by hugovk** [comment]
The next NumPy release will support Python 3.9. In the meantime, please could you revert the CI changes and only add the `setup.py` classifier?

**Comment by liisberg** [comment]
> The next NumPy release will support Python 3.9. In the meantime, please could you revert the CI changes and only add the `setup.py` classifier?

Done!

**Comment by hugovk** [comment]
Thanks, we're almost there... 

This didn't _revert_ (aka "undo") the changes in `.travis.yml`, rather it deleted `3.9`.

So now the end result is `3.9-dev` has also been deleted.

Please check the https://github.com/hugovk/pypistats/pull/172/files tab and update so that there are _only_ changes to `setup.py`.

**Comment by liisberg** [comment]
Sorry about that! Seems that I should not make commits before having my morning coffee..
Hope everything is in order now :-)

**Comment by hugovk** [comment]
:)

Looks good now, thank you!

**Pull request merged**
